[package]
name = "git-clean-untracked"
version = "0.2.0"
authors = ["Jonathan Delgado <hi@jon.soy> (https://jon.soy)"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"

